# 19.06.2014 Class 8 
> It was all about setting up jupyter notebook. 

# 20.06.2024 Class 9


# Numpy
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices,<br>along with a large collection of high-level mathematical functions to operate on these .
> python dosent support array directly that's why we use numpy.

## Why use **array** and not **list**?

- For working with data we need to be faster than normal list.<br>
- Accessing elements in list is slow because ***list in python are a linked-list (not simple list)***,<br> This makes list slower.
- **LISTS** are **heterogenous**( it can contain all kinds of datatypes) **ARRAYS** are **homogenous**( can only contain one kind of datatype at a time).<br> This makes list slower.



## How to install and import "numpy"?

In [1]:
# to install the package | need not run everytime
# pip install numpy

In [1]:
# to import nad use numpy
import numpy as np

## How to Create array?
### 1. Array from list?

In [3]:

ls = [5,2,9,6,2,4,7,3,9] # this is a list

# method "array" is given an argument variable "ls" which points to a list
# that list is converted to array
arr1 = np.array(ls) 
arr1

array([5, 2, 9, 6, 2, 4, 7, 3, 9])

### 2. Creating Array directly?

In [10]:
# directly giving a list as argument to 'array' method
arr2 = np.array([1,2,3,4]) 
arr2

# pay attention all elements are homogen

array([1, 2, 3, 4])

### 3. If list input in array method is not homogenous?

In [5]:
# one of the elements is "float"
arr3 = np.array([1,2,3,4.7]) 
arr3

# whole array is converted to float 
# as float can is capable to record both int and float value.

array([1. , 2. , 3. , 4.7])

In [6]:
# one of the elements is "str"

arr3 = np.array([1,2,3,'3ri']) 
arr3

# whole array is converted to "str" 
# as str can is capable to record as int and float and str value.

array(['1', '2', '3', '3ri'], dtype='<U11')

### 4. Using "arange()" to create array?
- SYNTAX : np.arange(start:stop:step)
> observe below ***array can be converted to matrix using .reshape()***

In [22]:
print( np.arange(4).reshape(2, 2))
print(np.arange(4, 10))
print(np.arange(4, 20, 3))

[[0 1]
 [2 3]]
[4 5 6 7 8 9]
[ 4  7 10 13 16 19]


## How create array matrix?

In [2]:
arrMat = np.array([[2,5,2,3,4],[4,7,5,6,7]])
arrMat

array([[2, 5, 2, 3, 4],
       [4, 7, 5, 6, 7]])

## + - * /  operators between matrices?
All these mathamatical operations can be performed on arrays of equal shape and size! 

In [23]:
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2) 
 
print('First array:') 
print(arr1)
 
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)
 
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))
 
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))
 
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))
 
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


## Shape in numpy? reshape?
- The information (num of rows, num of columns) in a matrix is that matrix's shape.

In [13]:
Mat = np.arange(60)
Mat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [14]:
reshapedMat = Mat.reshape(5,12)
reshapedMat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [15]:
reshapedMat0 = Mat.reshape(20,3)
reshapedMat0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [16]:
# if shape requested is not doable mathamatically it will give an error
reshapedMat1 = Mat.reshape(12,1)
reshapedMat1

ValueError: cannot reshape array of size 60 into shape (12,1)

## Size in numpy?
**Total elements in matrix = size of matrix**
- numpy.size() function count the number of elements along a given axis.

In [17]:
print(reshapedMat0)

# By default, give the total number of elements.
print(np.size(reshapedMat0))

#gives no. of rows along x-axis
print(np.size(reshapedMat0, 0)) 
 
#gives no. of columns along y-axis
print(np.size(reshapedMat0, 1)) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]
 [36 37 38]
 [39 40 41]
 [42 43 44]
 [45 46 47]
 [48 49 50]
 [51 52 53]
 [54 55 56]
 [57 58 59]]
60
20
3


## .ndim in numpy?
- tells us the dimensions of the array!

In [ ]:
# returns if it's 1D 2D 3D or more
arrMat.ndim

# 21.06.2024 Class 10

## Random()?

### Using "randint()" to create 1D array and "N"-D array?

In [61]:

# creates array with 4 random elements between 1 and 20
randint1Arr = np.random.randint(1,20,4)
randint1Arr

randintnArr = np.random.randint(10,size = (2,2,2,2))
randintnArr

array([[[[0, 8],
         [1, 8]],

        [[8, 2],
         [4, 0]]],


       [[[4, 8],
         [7, 2]],

        [[5, 9],
         [2, 3]]]])

#### It can be reshaped by reshape()!

In [67]:
randintArrReshaped = np.random.randint(2,20,3).reshape(10,10)
randintArrReshaped

ValueError: cannot reshape array of size 3 into shape (10,10)

#### Using "rand()" to create 1D  array & 2D array?

In [55]:
# 1D array
randArr = np.random.rand(10)    # array of 10 random floats 
print(randArr)

# 2D array


[0.18577548 0.28185294 0.03004171 0.28732843 0.67530494 0.57203115
 0.63435554 0.96774777 0.42923398 0.21545734 0.02262657 0.6761857
 0.01533134 0.14685735 0.49215131 0.13906981 0.59110804 0.213063
 0.79030051 0.08533445 0.42318526 0.07388942 0.43645226 0.73097467
 0.22756057 0.12229865 0.97260936 0.46915251 0.94401061 0.61972681
 0.09549825 0.02289557 0.88985621 0.60045369 0.51650274 0.98202153
 0.9416269  0.74519464 0.23270951 0.93512158 0.46196657 0.66868347
 0.46160063 0.11669982 0.13677991 0.79766947 0.98089289 0.32093973
 0.66077111 0.50288066 0.56646471 0.90669688 0.04728984 0.31600472
 0.82000621 0.40539149 0.92669539 0.60688797 0.3701703  0.56007779
 0.39722202 0.94220833 0.89035767 0.82398246 0.70243827 0.79467148
 0.15357004 0.19625909 0.16894806 0.72747441 0.04675709 0.65391001
 0.53793195 0.99418925 0.0390127  0.3284794  0.24098993 0.38105197
 0.87443705 0.2149889  0.06351634 0.47367616 0.77706851 0.95264417
 0.82079591 0.04298583 0.92441748 0.63519668 0.39946625 0.9818249

### Using **choice()** to create array? 
- #### Using for numbers?

In [52]:
ls = [3,5]

arrChoiceNum = np.random.choice(ls,10)
arrChoiceNum

array([3, 3, 3, 5, 3, 5, 3, 5, 5, 5])

- #### Using for Str?

In [16]:
lstr = ["ram","sham","lakshman","bharat"]

arrChoiceStr = np.random.choice(lstr,10)
arrChoiceStr

array(['ram', 'bharat', 'ram', 'ram', 'lakshman', 'bharat', 'sham',
       'sham', 'sham', 'ram'], dtype='<U8')

## **normal()?**

## **binomial()?**

## **.seed()?**
> scope of .seed():
- .ipynb : Cell
- .py : the whole page

In [20]:
a = np.random.seed(6)
a

## linespace()?

SyntaxError: invalid syntax (2465300508.py, line 1)

## **Array matrix slicing?**

## **array to csv ?**

---
---
[Advanced numpy](https://www.geeksforgeeks.org/python-numpy/)